config/routes.rb
Rails.application.routes.draw do

  resources :comments
  resources :users
  resources :subs
  resource :session, only: [:create, :new, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :string
#  user_id    :integer          not null
#  sub_id     :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ApplicationRecord
  validates :title, :user_id, :sub_id, presence: true

  belongs_to :sub,
    primary_key: :id,
    foreign_key: :sub_id,
    class_name: :Sub

  belongs_to :user,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :User
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  owner_id    :integer
#

class Sub < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :description, presence: true

  belongs_to :moderator,
    primary_key: :id,
    foreign_key: :owner_id,
    class_name: :User

  has_many :comments,
    primary_key: :id,
    foreign_key: :sub_id,
    class_name: :Comment

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord

  after_initialize :ensure_session_token

  validates :password, length: { minimum: 6, allow_nil: true }
  validates :password_digest, presence: true
  validates :session_token, presence: true
  validates :username, presence: true, uniqueness: true

  attr_reader :password

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    save
    self.session_token
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user
    user.is_password?(password) ? user : nil
  end

  has_many :subs,
    primary_key: :id,
    foreign_key: :owner_id,
    class_name: :Sub

  has_many :comments,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :Comment

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :require_log_in, :logged_in?

  def login!
    session[:session_token] = current_user[session: session[:session_token]]
  end

  def current_user
    @current_user ||= User.find_by(session[:session_token])
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?
    !!current_user
  end

  def require_log_in
    redirect_to new_session_url unless logged_in?
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.find_by_credentials(username, password)
    if user
      login!
      redirect_to subs_url
    else
      flash[:errors] = ["Invalid username or password"]
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController

  before_action :require_log_in

  def new
    render :new
  end

  def create
    sub = Sub.new(sub_params)
    sub.owner_id = current_user.id
    if sub.save
      redirect_to sub_url(sub)
    else
      flash[:errors] = sub.errors.full_messages
      render :new
    end
  end

  def destroy
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def index
    @subs = Sub.all
  end

  def update
    return nil unless current_user.subs.include?(Sub.find(params[:id]))
    sub = Sub.find(params[:id])
    if sub.update_attributes(sub_params)
       redirect_to sub_url(sub)
    else
       flash[:errors] = sub.errors.full_messages
       render :edit
    end
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.new(user_params)
    if user.save
      login!
      redirect_to subs_url
    else
      flash[:errors] = user.errors.full_message
      render :new
    end
  end

  def delete
  end

  def index
  end

  def show
    @user = User.find_by(id: id)
  end

  def update
  end

  def edit
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/new.html.erb
<h4>Add Comment</h4>

<form action="<%=comment_url(sub)%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

  <label>Comment
    <label>Title
      <input type="text" name="comment[title]">
    </label>
    <label>URL
      <input type="text" name="comment[url]">
    </label>
    <textarea name="comment[content]" rows="8" cols="80"></textarea>
  </label>

</form>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <% if current_user %>
    <%= "Welcome, #{current_user.username}" %>
    <%= button_to "Log Out", session_url, method: :delete %>
  <% else %>
    <%= link_to "Sign Up", new_user_url, method: :get %>
    <%= link_to "Log In", new_session_url, method: :get %>
  <% end %>

  <ul>
  <% flash[:errors].try(:each) do |error| %>
    <li> <%= error %> </li>
  <% end %>
  </ul>

  <body>
    <%= yield %>
  </body>
</html>

app/views/subs/destroy.html.erb
<h1>Subs#destroy</h1>
<p>Find me in app/views/subs/destroy.html.erb</p>

app/views/subs/edit.html.erb
<h3>Edit Sub</h3>

<form action="<%=sub_url(@sub)%>" method="post">
  <input type="hidden" name="_method" value="PATCH">

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Title
    <input type="text" name="sub[title]" value="<%= @sub.title  %>">
  </label>

  <label>Description
    <textarea name="sub[description]" rows="8" cols="80">
      <%= @sub.description %>
    </textarea>
  </label>

  <input type="submit" value="Commit Edits">

</form>

app/views/subs/index.html.erb
<h1>Subs:</h1>

<ul>
<% @subs.try(:each) do |sub| %>
<li>
<%= link_to sub.title, sub_url(sub), method: :get %>
<%= sub.description %>
<%= button_to 'Edit', edit_sub_url(sub), method: :get %>
</li>
<% end %>
</ul>

<%= link_to 'Make New Sub!', new_sub_url, method: :get %>

app/views/subs/new.html.erb
<h3>Create Sub</h3>

<form action="/subs" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Title
    <input type="text" name="sub[title]">
  </label>

  <br>

  <label>Description
    <textarea name="sub[description]" rows="8" cols="80"></textarea>
  </label>

  <input type="submit" value="Create Sub!">

</form>

app/views/subs/show.html.erb
<h3><%=@sub.title%></h3>

<%= @sub.description %>

<%= button_to "Add Comment", new_comment_url , sub: @sub , method: :get %>

<% @sub.comments.try(:each) do |comment| %>
<ul>
<li><%= comment.user %></li>
<li><%= comment.content comment.url %></li>
</ul>
<% end %>

<br><br>
<%= link_to "List of Subs", subs_url, method: :get %>

app/views/subs/update.html.erb
<h1>Subs#update</h1>
<p>Find me in app/views/subs/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h3>Sign Up</h3>

<form action="/users" method="post">

  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <label>Username
    <input type="text" name="user[username]" value="">
  </label>
  <label>Password
    <input type="password" name="user[password]" value="">
  </label>

  <input type="submit" value="Sign Up">
</form>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>